<?php

/**
 * BaseCrossword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property boolean $is_public
 * @property boolean $is_activated
 * @property Doctrine_Collection $CrosswordWords
 * @property Doctrine_Collection $UserAnswer
 * 
 * @method string              getTitle()          Returns the current record's "title" value
 * @method string              getDescription()    Returns the current record's "description" value
 * @method boolean             getIsPublic()       Returns the current record's "is_public" value
 * @method boolean             getIsActivated()    Returns the current record's "is_activated" value
 * @method Doctrine_Collection getCrosswordWords() Returns the current record's "CrosswordWords" collection
 * @method Doctrine_Collection getUserAnswer()     Returns the current record's "UserAnswer" collection
 * @method Crossword           setTitle()          Sets the current record's "title" value
 * @method Crossword           setDescription()    Sets the current record's "description" value
 * @method Crossword           setIsPublic()       Sets the current record's "is_public" value
 * @method Crossword           setIsActivated()    Sets the current record's "is_activated" value
 * @method Crossword           setCrosswordWords() Sets the current record's "CrosswordWords" collection
 * @method Crossword           setUserAnswer()     Sets the current record's "UserAnswer" collection
 * 
 * @package    crosswords
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCrossword extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('crossword');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Word as CrosswordWords', array(
             'local' => 'id',
             'foreign' => 'crossword_id'));

        $this->hasMany('UserAnswer', array(
             'local' => 'id',
             'foreign' => 'crossword_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fztaggable0 = new fzTaggable();
        $this->actAs($timestampable0);
        $this->actAs($fztaggable0);
    }
}