<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $title
 * @property string $meta
 * @property string $description
 * @property string $text
 * 
 * @method string getCode()        Returns the current record's "code" value
 * @method string getTitle()       Returns the current record's "title" value
 * @method string getMeta()        Returns the current record's "meta" value
 * @method string getDescription() Returns the current record's "description" value
 * @method string getText()        Returns the current record's "text" value
 * @method Page   setCode()        Sets the current record's "code" value
 * @method Page   setTitle()       Sets the current record's "title" value
 * @method Page   setMeta()        Sets the current record's "meta" value
 * @method Page   setDescription() Sets the current record's "description" value
 * @method Page   setText()        Sets the current record's "text" value
 * 
 * @package    crosswords
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('meta', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('text', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}