<?php

/**
 * BaseAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $word_id
 * @property string $text
 * @property integer $answer_id
 * @property Word $Word
 * @property UserAnswer $UserAnswer
 * 
 * @method integer    getWordId()     Returns the current record's "word_id" value
 * @method string     getText()       Returns the current record's "text" value
 * @method integer    getAnswerId()   Returns the current record's "answer_id" value
 * @method Word       getWord()       Returns the current record's "Word" value
 * @method UserAnswer getUserAnswer() Returns the current record's "UserAnswer" value
 * @method Answer     setWordId()     Sets the current record's "word_id" value
 * @method Answer     setText()       Sets the current record's "text" value
 * @method Answer     setAnswerId()   Sets the current record's "answer_id" value
 * @method Answer     setWord()       Sets the current record's "Word" value
 * @method Answer     setUserAnswer() Sets the current record's "UserAnswer" value
 * 
 * @package    crosswords
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('answer');
        $this->hasColumn('word_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('text', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('answer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Word', array(
             'local' => 'word_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('UserAnswer', array(
             'local' => 'answer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}