<?php

/**
 * AnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Answer');
    }
    
    /**
     * 
     * @param int $user_id
     * @param int $crosswrord_id
     */
    public function clearAnswerWords( $answer_id ) {
    	
    	if ( empty( $answer_id ) ) {
    		throw new InvalidArgumentException( 'User answer id is missing' );
    	}
    	
    	$query = $this->getQueryObject();
    	
		return $query->delete()
    		->andWhere( 'answer_id = ?', $answer_id )
		 	->fetchArray();
    }
}