<?php

/**
 * Crossword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    crosswords
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Crossword extends BaseCrossword
{
	/**
	 * 
	 * Enter description here ...
	 */
	public function getWords() {
		return Doctrine_Query::create()
			->from('Word w')
			->where('w.crossword_id = ?', $this->getId())
			->orderBy( 'w.y ASC, w.x ASC' )
			->execute();
	}
}
