<?php

/**
 * UserAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserAnswer');
    }

    /**
     * 
     * Enter description here ...
     * @param int $user_id
     * @param int $crossword_id
     * @throws InvalidArgumentException
     */
    public function getUserAnswer( $user_id, $crossword_id ) {
    	
    	if ( empty( $user_id ) || !is_numeric( $user_id ) ) {
    		throw new InvalidArgumentException( 'User id is missing' );
    	}
    	
    	if ( empty( $crossword_id ) || !is_numeric( $crossword_id ) ) {
    		throw new InvalidArgumentException( 'Crossword id is missing' );
    	}
    	
    	$query = $this->getQueryObject();
    	
    	return $query
    		->where( 'crossword_id = ?', $crossword_id )
    		->andWhere( 'user_id = ?', $user_id )
    		->fetchOne();
    } 
}