<?php
/**
 * UserAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    crosswords
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserAnswer extends BaseUserAnswer {

	/**
	 * Возвращает ответы пользователя
	 *  
	 */
	public function getWords() {
		return Doctrine_Query::create()
			->from('Answer a')
			->where('a.answer_id = ?', $this->getId())
			->execute();
	}
	
	/**
	 * Проверка правильности заполнения
	 * @return bool
	 */
	public function isCorrect(){
		
		$user_words = $this->getWords();
		
		$crossword_words = $this->getCrossword()->getWords();

		if ( count( $crossword_words ) <= 0 ) {
			return false;
		}
		
		foreach ( $crossword_words as $word ) {
			$word_correct = false;
			
			foreach ( $user_words as $user_word ) {

				if ( $word->getId() == $user_word->getWordId() && $word->getWord() == $user_word->getText() ){
					$word_correct = true;
					break;
				}
			}
			
			if ( !$word_correct ) {
				return false;
			}
		}
		
		return true;
	}
}