# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: front, action: index }

constructor:
  url:     /constructor/:crossword_id
  class:   sfDoctrineRoute
  options: { model: Crossword, type: object }
  param:   { module: constructor, action: index }
  requirements:
    crossword_id: \d+
    sf_method: [get]

constructor_save:
  url:     /constructor/:crossword_id/save
  class:   sfDoctrineRoute
  options: { model: Crossword, type: object }
  param:   { module: constructor, action: save }
  requirements:
    crossword_id: \d+
    sf_method: [post]

constructor_resolve:
  url:     /resolve/:crossword_id/
  class:   sfDoctrineRoute
  options: { model: Crossword, type: object }
  param:   { module: resolve, action: resolve }
  requirements:
    crossword_id: \d+
    sf_method: [get]

fz_tag_show:
  url:     /tags/:name
  class:   sfDoctrineRoute
  options: { model: fzTag, type: object }
  param:   { module: crossword, action: tag }

save_answer:
  url:     /resolve/:crossword_id/save
  class:   sfDoctrineRoute
  options: { model: Crossword, type: object }
  param:   { module: resolve, action: save }
  requirements:
    crossword_id: \d+
    sf_method: [post]

#auth rules

login:
  url: /login
  param:   { module: auth, action: index }

oauth_twitter:
  url: /auth/success/twitter
  param:   { module: auth, action: success, service: twitter }

oauth_facebook:
  url: /auth/success/facebook
  param:   { module: auth, action: success, service: facebook }

auth_oauth:
  url: /auth/:service
  param:   { module: auth, action: connect }

logout:
  url: /logout
  param:   { module: auth, action: logout }

register: 
  url: /register
  param:   { module: auth, action: index }

#user rules

profile: 
  url: /profile
  param:   { module: profile, action: index }
 

# generic rules
# please, remove them by adding more specific rules

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
