resolveSuccess:
  stylesheets: [sunny/jquery-ui-1.8.11.custom.css,constructor.css,resolver.css]
  javascripts: [jquery-1.5.1.min.js, common.js, point.js, abstract_word_view.js, mapped_word_view.js, messages_helper.js, crossword.js, mapped_word_item.js, abstract_crossword_area.js, crossword_resolver.js, crossword_area.js]