Crossword:
  actAs: { Timestampable: ~, fzTaggable: ~}
  columns:
    title:        { type: string(255) }
    description:  { type: string(4000), notnull: true }
    is_public:    { type: boolean, notnull: true, default: 1 }
    is_activated: { type: boolean, notnull: true, default: 0 }
    user_id:      { type: integer, notnull: true }
  relations:
    sfGuardUser: { onDelete: CASCADE, local: user_id, foreign: id }

Word:
  actAs: { Timestampable: ~ }
  columns:
    word: {type: string(255)}
    definition: {type: string(255)}
    crossword_id: { type: integer, notnull: true }
    horisontal: { type: boolean, notnull: true, default: 0 }
    x: { type: integer, notnull: true }
    y: { type: integer, notnull: true }
  relations:
    Crossword: { onDelete: CASCADE, local: crossword_id, foreign: id, foreignAlias: CrosswordWords }
    
Answer:
  columns:
    word_id: { type: integer, notnull: true }
    text: {type: string(255)}
    answer_id: { type: integer, notnull: true }
  relations:
    Word: { onDelete: CASCADE, local: word_id, foreign: id }
    UserAnswer: { onDelete: CASCADE, local: answer_id, foreign: id } 
    
UserAnswer: 
  actAs: { Timestampable: ~ }
  columns:
    user_id: { type: integer, notnull: true }
    crossword_id: { type: integer, notnull: true }
    is_correct: { type: boolean, notnull: true, default: false }
  relations:
    Crossword: { onDelete: CASCADE, local: crossword_id, foreign: id }
    sfGuardUser: { onDelete: CASCADE, local: user_id, foreign: id } 
  